apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: auth-service-dev
  labels:
    app: auth-service-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service-dev
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: auth-service-dev
    spec:
      containers:
      - name: auth-service-dev-container
        image: edwardkcyu/auth-service:1.0.0
        imagePullPolicy: Always
        env:
        - name: NODE_ENV
          value: "development"
        - name: PORT
          value: "6020"
        ports:
        - containerPort: 6020
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service-dev
  type: ClusterIP
  ports:
    - port: 6020
  