apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-service-dev
  labels:
    app: hello-service-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-service-dev
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: hello-service-dev
    spec:
      containers:
      - name: hello-service-dev-container
        image: edwardkcyu/hello-service:1.0.0
        imagePullPolicy: Always
        env:
        - name: NODE_ENV
          value: "development"
        - name: PORT
          value: "6010"
        - name: AUTH_SERVICE_URL
          value: 'auth-service.default.svc.cluster.local'
        
        ports:
        - containerPort: 6010
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  selector:
    app: hello-service-dev
  type: ClusterIP
  ports:
    - port: 6010
  